server:
  port: 9090
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: kshitij_db
    password: oracle
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: db.ons.pool
      connection-wait-timeout: 60
      min-pool-size: 0
      max-pool-size: 25
      property-cycle: 60
      inactive-connection-timeout: 300
      max-connection-reuse-count: 100
      timeout-check-interval: 60
      fast-connection-failover-enabled: true
      o-n-s-configuration: nodes=db.ons.node
      validate-connection-on-borrow: true
      s-q-l-for-validate-connection: SELECT 1 from dual
      max-statements: 0
  jpa:
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poc_mongo
      authentication-database: admin
      username: poc_mongo
      password: poc_mongo